# Use the Python image
FROM registry.redhat.io/ubi9/python-39@sha256:6f89c966a1939d3fcd8919f1e823f1794721e68fb3b31388230529ff622eebef

USER 0
RUN chown -R 1001:0 ./ && \
    yum install -y mesa-libGL && \
    yum clean all && \
    rm -rf /var/cache/yum

USER 1001

RUN pip install --no-cache-dir jupyterlab ultralytics

